imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: cs

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

knp_menu:
    twig:
        template: "@Amonthia/Menu/Menu.html.twig"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
    orm:
        entity_managers:
            default:
#                        auto_generate_proxy_classes: "%kernel.debug%"
                naming_strategy: doctrine.orm.naming_strategy.underscore
#                auto_mapping: true
                mappings:
#                            SonataMediaBundle: ~
                    AmonthiaBundle:
                        type: annotation
                    UserBundle:
                        type: annotation
                    FOSUserBundle:
                        type: ~
#                            SonataClassificationBundle: ~
#    orm:
#        auto_generate_proxy_classes: "%kernel.debug%"
#        naming_strategy: doctrine.orm.naming_strategy.underscore
#        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

assetic:
    filters:
        less:
            node: /usr/bin/nodejs
            node_paths: [/usr/local/lib/node_modules]
            apply_to: '\.less$'
        cssrewrite: ~
    assets:
        bootstrap_css:
                inputs:
                    - %kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less
                    - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
                    - %kernel.root_dir%/../src/Night/AmonthiaBundle/Resources/css/main.css
                    - %kernel.root_dir%/../src/Night/AmonthiaBundle/Resources/css/sidebar.css
                    - %kernel.root_dir%/../src/Night/AmonthiaBundle/Resources/css/bootstrap-social.css

braincrafted_bootstrap:
    output_dir:
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    css_preprocessor: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: true
        twig: true
        knp_menu: false
        knp_paginator: true
    customize:
        variables_file: ~
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
          address:  'registrator@publeash.nightnr.com'
          sender_name:  'PubLeash - Registrator'
    registration:
          confirmation:
            enabled: true
          form:
            type: app_user_registration
    profile:
          form:
            type: fos_user_profile

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    connect:
            account_connector: amonthia.user_provider
    fosub:
            username_iterations: 30
            properties:
                facebook:    facebook_id
                google: google_id
    resource_owners:
        facebook:
            type:                facebook
            client_id:           657001304473350
            client_secret:       8fb3bbca8f2ddb80894dc06dc81ca22f
            scope:               "email"
            options:
                display: popup
        google:
            type: google
            client_id: "256003520636-bftpaa593b5k2kbn051cccbdvo9l5pu9.apps.googleusercontent.com"
            client_secret: "AMgXcbNlSgnUBPV_UI52xpxi"
            scope: "email profile"