services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    app.form.registration:
        class: UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
        arguments: [Night\AmonthiaBundle\Entity\User]
    app.form.profile:
            class: UserBundle\Form\Type\ProfileFormType
            tags:
                - { name: form.type, alias: app_user_profile }
            arguments: [Night\AmonthiaBundle\Entity\User]