services:
#    amonthia.example:
#        class: Night\AmonthiaBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

  amonthia.user_provider:
        class: Night\AmonthiaBundle\Service\UserProvider
        arguments: [@fos_user.user_manager, "@doctrine.orm.entity_manager", @session, {facebook: facebook_id, google: google_id}]

  api:
      class: Night\AmonthiaBundle\Service\Api
      arguments: [@doctrine.orm.default_entity_manager]

  api_setting:
      class: Night\AmonthiaBundle\Service\ApiCommands\Setting
      arguments: [@doctrine.orm.default_entity_manager]
      tags:
            - { name: api.service }